<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>netstandard2.1;net10.0</TargetFrameworks>
        <Nullable>enable</Nullable>
        <LangVersion>default</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Misirka\Misirka.csproj" />
    </ItemGroup>

    <PropertyGroup Condition="'$(TargetFramework)' == 'net10.0'">
        <IsTrimmable>true</IsTrimmable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="System.Text.Json" Version="10.0.12" />
    </ItemGroup>

</Project>
